1st_blur_multiplier: 0.65
absolute_threshold: 80
auto_detect_scale: true
cell_blur: 81
cell_outline_colour: [255, 255, 255]
cell_perimeter: 150
circularity_threshold: 0.8
cluster_circularity_threshold: 0.3
cluster_dot_colour: [36, 12, 255]
cluster_dot_contour_thickness: 2
difference_threshold: 10
dilate_size: 15
dot_blur: 13
dot_threshold: 45
dots_needed_for_cluster: 1.5
dynamic_circularity: true
dynamic_threshold: true
min_area: 120
min_area_of_entire_image_cell: 0.05
only_run_new_images: true
output_directory: D:\HW\gold_nanoparticle_TC\Frontend\output
output_image_type: jpg
predict_best_settings: true
prevent_cell_touching_border: true
prevent_false_positives: true
required_circularity_lowering_per_dot: 0.25
scale: 0.5
show_cell_outline: false
single_dot_colour: [36, 255, 12]
single_dot_contour_thickness: 2
